//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ShopOrderDetail = new HashSet<ShopOrderDetail>();
        }
    
        public int ID { get; set; }
        public string ProductArticle { get; set; }
        public string ProductName { get; set; }
        public string ProductUnit { get; set; }
        public int ProductPrice { get; set; }
        public int ProductSupplierID { get; set; }
        public Nullable<int> ProductManufacturerID { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public int ProductDiscount { get; set; }
        public int ProductInStock { get; set; }
        public string ProductDescription { get; set; }
        public string ProductPhotoPath { get; set; }
    
        public virtual ProductSupplier ProductSupplier { get; set; }
        public virtual ProductManufacturer ProductManufacturer { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopOrderDetail> ShopOrderDetail { get; set; }

        public int ProductTotalPrice
        {
            get
            {
                return ProductPrice - (ProductPrice * ProductDiscount / 100);
            }
        }
    }
}
