//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesShop
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Runtime.Remoting.Contexts;
    using System.Text;
    using System.Windows.Controls.Primitives;

    public partial class ShopOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopOrder()
        {
            this.ShopOrderDetail = new HashSet<ShopOrderDetail>();
        }
    
        public int ID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int PickupPointID { get; set; }
        public int ClientID { get; set; }
        public int Code { get; set; }
        public int OrderStatusID { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual PickupPoint PickupPoint { get; set; }
        public virtual ShopUser ShopUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopOrderDetail> ShopOrderDetail { get; set; }

        public List<ShopOrderDetail> ShopOrderDetailList
        {
            get
            {
                return new List<ShopOrderDetail>(ShopOrderDetail);
            }
        }

        public string OrderArticle
        {
            get
            {
                StringBuilder OrderArticle = new StringBuilder();
                for (int count = 0; count < ShopOrderDetailList.Count; count = count + 1)
                {
                    ShopOrderDetail detail = ShopOrderDetailList[count];
                    OrderArticle.Append(detail.Product.ProductArticle);
                    OrderArticle.Append(",");
                    OrderArticle.Append(detail.Amount);
                    if (count != ShopOrderDetailList.Count - 1)
                    {
                        OrderArticle.Append(", ");
                    }
                }
                return OrderArticle.ToString();
            }
        }
    }
}
