//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopOrderDetail : IComparable<ShopOrderDetail>
    {
        public int ID { get; set; }
        public int ShopOrderID { get; set; }
        public int ProductID { get; set; }
        public int Amount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ShopOrder ShopOrder { get; set; }

        public int CompareTo(ShopOrderDetail other)
        {
            return ID.CompareTo(other.ID);
        }
    }
}
