CREATE DATABASE Emelyanenko_ShoesShop;

GO

USE Emelyanenko_ShoesShop;

CREATE TABLE UserRole (ID INT PRIMARY KEY IDENTITY(0, 1), Name VARCHAR(50) NOT NULL);
CREATE TABLE ShopUser (ID INT PRIMARY KEY IDENTITY(0, 1), UserRoleID INT REFERENCES UserRole NOT NULL, UserFIO VARCHAR(150) NOT NULL, UserLogin VARCHAR(150) NOT NULL, UserPassword VARCHAR(150) NOT NULL);

CREATE TABLE ProductSupplier (ID INT PRIMARY KEY IDENTITY(0, 1), Name VARCHAR(50) NOT NULL);
CREATE TABLE ProductManufacturer (ID INT PRIMARY KEY IDENTITY(0, 1), Name VARCHAR(50) NOT NULL);
CREATE TABLE ProductCategory (ID INT PRIMARY KEY IDENTITY(0, 1), Name VARCHAR(50) NOT NULL);
CREATE TABLE Product (ID INT PRIMARY KEY IDENTITY(0, 1), ProductArticle VARCHAR(50) NOT NULL, ProductName VARCHAR(100) NOT NULL, ProductUnit VARCHAR(50), ProductPrice INT NOT NULL, ProductSupplierID INT REFERENCES ProductSupplier NOT NULL, ProductManufacturerID INT REFERENCES ProductManufacturer, ProductCategoryID INT REFERENCES ProductCategory, ProductDiscount INT NOT NULL, ProductInStock INT NOT NULL, ProductDescription VARCHAR(200) NOT NULL, ProductPhotoPath VARCHAR(200));

CREATE TABLE PickupPoint (ID INT PRIMARY KEY IDENTITY(0, 1), PostIndex INT, City VARCHAR(50), Street VARCHAR(50), HouseIndex INT);
CREATE TABLE OrderStatus (ID INT PRIMARY KEY IDENTITY(0, 1), Name VARCHAR(50) NOT NULL);
CREATE TABLE ShopOrder (ID INT PRIMARY KEY IDENTITY(0,1), OrderDate DATE NOT NULL, DeliveryDate DATE NOT NULL, PickupPointID INT REFERENCES PickupPoint NOT NULL, ClientID INT REFERENCES ShopUser NOT NULL, Code INT NOT NULL, OrderStatusID INT REFERENCES OrderStatus NOT NULL);
CREATE TABLE ShopOrderDetail (ID INT PRIMARY KEY IDENTITY(0,1), ShopOrderID INT REFERENCES ShopOrder NOT NULL, ProductID INT REFERENCES Product NOT NULL, Amount INT NOT NULL);